### ISSUE TITLE
cannot run npm install

### ISSUE THREAD

**Issue by goprojojo** [s6joui/MirrorOS#3]
I followed the manual installation but cannot execute yarn install or npm install:

pi@RPI3B:~ $ cd MirrorOS
pi@RPI3B:/MirrorOS $ npm install
bash: npm: command not found

I have the latest Raspbian Stretch on Raspberry Pi 3

**Comment by cu-kha** [comment]
Hi, you may need to install nodejs to run npm. Check out nodejs.org

**Comment by goprojojo** [comment]
Thanx for your quick reply. I've installed node.js ( sudo apt-get install nodejs npm ) but still having issues running npm:

pi@RPI3B:~ $ sudo npm install
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 4.9.41-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/package.json
npm ERR! syscall open
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
pi@RPI3B:~ $

**Comment by cu-kha** [comment]
First you should cd to the directory where you cloned the MirrorOS
repository.

2017-09-20 14:36 GMT+02:00 goprojojo <notifications@github.com>:

**Comment by goprojojo** [comment]
I have the latest node.js and npm installed. I did as you told but still no avail:


pi@RPI3B:~ $ cd MirrorOS
pi@RPI3B:~/MirrorOS $ npm start

> MirrorOS@0.1.0 start /home/pi/MirrorOS
> ./system/starter.sh


npm ERR! Linux 4.9.41-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! MirrorOS@0.1.0 start: `./system/starter.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MirrorOS@0.1.0 start script './system/starter.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the MirrorOS package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./system/starter.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs MirrorOS
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls MirrorOS

**Comment by VH-Tech** [comment]
Hi, I am also facing an issue similar to this:

pi@raspberrypi:~/MirrorOS $ npm install
npm WARN package.json MirrorOS@0.1.0 No repository field.
npm WARN package.json MirrorOS@0.1.0 No license field.
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'electron'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.9.80-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/MirrorOS
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/MirrorOS/npm-debug.log
npm ERR! not ok code 0
 
Thanks

**Comment by VH-Tech** [comment]
Hi solved the problem.
Its an issue with the OS .
Actually I switched to raspbian jessie and now I am able to install dependencies and start the program .

**Comment by cu-kha** [comment]
Solution: 
Use the latest NPM version. You can install it with node following these instructions: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
