### ISSUE TITLE
Just shows starting

### ISSUE THREAD

**Issue by VH-Tech** [s6joui/MirrorOS#4]
Hi,
I successfully installed MirrorOS on my pi and have finished installing all the dependencies.
But when I do "npm start ".
I just receive an electron window with a single word "starting...". I waited for about half an hour but nothing came up.
Can anybody please help me??

**Comment by cu-kha** [comment]
Hello, you should rename ```config.json.example``` to ```config.json```
Optionally, you can fill it in with your API keys.

**Comment by cu-kha** [comment]
In the latest version (0.2.0) the file is automatically generated so I'm gonna code this issue for now.
